name: Build ZMK firmware
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "keymap-drawer/**"

jobs:
  build:
    uses: https://raw.githubusercontent.com/zmkfirmware/zmk/refs/heads/main/.github/workflows/build-user-config.yml # point to github
