name: Build ZMK firmware
on:
  workflow_dispatch: 
  pull_request:
    types: [closed]

jobs:
  build:
    if: ${{ github.event.pull_request.merged && github.event.pull_request.base.ref == 'main' }}
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
